#
b D:\iTeaBlend\db\iTeaBlend.b1 f 2176
b D:\iTeaBlend\db\iTeaBlend.b2 f 1024
b D:\iTeaBlend\db\iTeaBlend.b3 f 128
b D:\iTeaBlend\db\iTeaBlend.b4 f 1024
b D:\iTeaBlend\db\iTeaBlend.b5
#
d "Schema Area":6,64;1 D:\iTeaBlend\db\iTeaBlend.d1
#
d "Cust01":7,64;1 D:\iTeaBlend\db\iTeaBlend_7.d1 f 8192
d "Cust01":7,64;1 D:\iTeaBlend\db\iTeaBlend_7.d2
#
d "Cust02":8,64;8 D:\iTeaBlend\db\iTeaBlend_8.d1 f 8192
d "Cust02":8,64;8 D:\iTeaBlend\db\iTeaBlend_8.d2
